<?php

return 
[
    [
        "id" => 1,
        "user_id" => 2,
        "title" => "Appartamento vista Mare",
        "slug" => "appartamento-vista-mare",
        "price_per_night" => 250,
        "rooms_number" => 3,
        "beds_number" => 3,
        "bathrooms_number" => 2,
        "square_meters" => 100,
        "address" => "Viale Verona,82,Trento",
        "latitude" => "46,024508",
        "longitude" => "11,075106",
        "cover_img" => "img/app_1/cover-img-app-1.jpg",
        "description" => "L'appartamento vista mare è un elegante rifugio costiero, situato in una posizione privilegiata con vista panoramica sull'infinito azzurro dell'oceano. Questo spazio luminoso e arieggiato è caratterizzato da ampie finestre che si affacciano sul mare, permettendo alla luce naturale di inondare gli interni. L'arredamento è ispirato alla tranquillità del mare, con tonalità di blu e turchese che si mescolano con il bianco per creare un'atmosfera rilassante.",
        "visible" => 1,
    ],
    [   
        "id" => 2,
        "user_id" => 2,
        "title" => "Appartamento vista Montagna",
        "slug" => "appartamento-vista-montagna",
        "price_per_night" => 110,50,
        "rooms_number" => 2,
        "beds_number" => 2,
        "bathrooms_number" => 1,
        "square_meters" => 70,
        "address" => "Viale Verona,60,Trento",
        "latitude" => "46,024508",
        "longitude" => "11,075106",
        "cover_img" => "img/app_2/cover-img-app-2.jpg",
        "description" => "L'appartamento vista montagna è un elegante rifugio costiero, situato in una posizione privilegiata con vista panoramica sull'infinito azzurro dell'oceano. Questo spazio luminoso e arieggiato è caratterizzato da ampie finestre che si affacciano sul mare, permettendo alla luce naturale di inondare gli interni. L'arredamento è ispirato alla tranquillità del mare, con tonalità di blu e turchese che si mescolano con il bianco per creare un'atmosfera rilassante.",
        "visible" => 1,
    ],
    [
        "id"=> 3,
        "user_id"=> 1,
        "title"=> "Villa con Piscina",
        "slug"=> "villa-con-piscina",
        "price_per_night"=> 350,
        "rooms_number"=> 5,
        "beds_number"=> 6,
        "bathrooms_number"=> 4,
        "square_meters"=> 250,
        "address"=> "Via delle Palme,50,Roma",
        "latitude"=> "41.902783",
        "longitude"=> "12.496365",
        "cover_img"=> "img/app_3/cover-img-app-3.jpg",
        "description"=> "Questa lussuosa villa con piscina è l'ideale per una vacanza di relax. Con un ampio giardino, una piscina privata e spazi interni eleganti, questa proprietà offre il massimo comfort e lusso.",
        "visible"=> 1
    ],
    [
        "id"=> 4,
        "user_id"=> 1,
        "title"=> "Chalet Accogliente",
        "slug"=> "chalet-accogliente",
        "price_per_night"=> 180,
        "rooms_number"=> 2,
        "beds_number"=> 4,
        "bathrooms_number"=> 2,
        "square_meters"=> 120,
        "address"=> "Via della Montagna,10,Milano",
        "latitude"=> "45.464664",
        "longitude"=> "9.188540",
        "cover_img"=> "img/app_4/cover-img-app-4.jpg",
        "description"=> "Questo chalet accogliente è perfetto per una fuga in montagna. Con una vista mozzafiato sulle cime delle montagne e un camino caldo e accogliente, è il luogo ideale per rilassarsi.",
        "visible"=> 1
    ],
    [
        "id"=> 5,
        "user_id"=> 3,
        "title"=> "Appartamento Storico",
        "slug"=> "appartamento-storico",
        "price_per_night"=> 200,
        "rooms_number"=> 4,
        "beds_number"=> 4,
        "bathrooms_number"=> 3,
        "square_meters"=> 150,
        "address"=> "Piazza del Duomo,50,Firenze",
        "latitude"=> "43.773543",
        "longitude"=> "11.256881",
        "cover_img"=> "img/app_5/cover-img-app-5.jpeg",
        "description"=> "Questo appartamento storico offre un'esperienza autentica nel cuore di Firenze. Con affreschi originali e una vista sulla cattedrale, è un sogno per gli amanti dell'arte e della cultura.",
        "visible"=> 1
    ],
    [
        "id"=> 6,
        "user_id"=> 3,
        "title"=> "Cottage Affacciato sul Lago",
        "slug"=> "cottage-affacciato-sul-lago",
        "price_per_night"=> 280,
        "rooms_number"=> 3,
        "beds_number"=> 5,
        "bathrooms_number"=> 2,
        "square_meters"=> 180,
        "address"=> "Lungolago,80,Como",
        "latitude"=> "45.810107",
        "longitude"=> "9.085156",
        "cover_img"=> "img/app_6/cover-img-app-6.jpeg",
        "description"=> "Questo cottage affacciato sul lago offre una vista mozzafiato sul Lago di Como. Con un accesso diretto al lago e un giardino ben curato, è il luogo ideale per una vacanza in riva al lago.",
        "visible"=> 1
    ],
    [
        "id"=> 7,
        "user_id"=> 4,
        "title"=> "Appartamento nel Centro Storico",
        "slug"=> "appartamento-centro-storico",
        "price_per_night"=> 150,
        "rooms_number"=> 2,
        "beds_number"=> 3,
        "bathrooms_number"=> 1,
        "square_meters"=> 90,
        "address"=> "Via del Corso,52,Napoli",
        "latitude"=> "40.852180",
        "longitude"=> "14.268110",
        "cover_img"=> "img/app_7/cover-img-app-7.jpeg",
        "description"=> "Questo appartamento nel centro storico di Napoli è situato in una posizione ideale per esplorare la città. Con una vista sulla Piazza del Plebiscito, è il luogo perfetto per scoprire il patrimonio storico e culturale della città.",
        "visible"=> 1
    ],
    [
        "id"=> 8,
        "user_id"=> 4,
        "title"=> "Casa Sulla Spiaggia",
        "slug"=> "casa-sulla-spiaggia",
        "price_per_night"=> 300,
        "rooms_number"=> 4,
        "beds_number"=> 6,
        "bathrooms_number"=> 3,
        "square_meters"=> 200,
        "address"=> "Lungomare,45,Cagliari",       
        "latitude"=> "39.223559",
        "longitude"=> "9.112839",
        "cover_img"=> "img/app_8/cover-img-app-8.jpeg",
        "description"=> "Questa casa sulla spiaggia è un'oasi di relax. Con accesso diretto alla spiaggia e una terrazza con vista sull'oceano, è il luogo ideale per una vacanza balneare.",
        "visible"=> 1
    ],
    [
        "id"=> 9,
        "user_id"=> 5,
        "title"=> "Appartamento con Vista sui Monti",
        "slug"=> "appartamento-vista-monti",
        "price_per_night"=> 170,
        "rooms_number"=> 2,
        "beds_number"=> 4,
        "bathrooms_number"=> 2,
        "square_meters"=> 120,
        "address"=> "Via Panoramica,85,Bologna",
        "latitude"=> "44.494887",
        "longitude"=> "11.342616",
        "cover_img"=> "img/app_9/cover-img-app-9.jpeg",
        "description"=> "Questo appartamento offre una vista spettacolare sulle montagne circostanti. Con una terrazza panoramica e una posizione tranquilla, è l'ideale per una fuga nella natura.",
        "visible"=> 1
    ],
    [
        "id"=> 10,
        "user_id"=> 5,
        "title"=> "Casa di Campagna con Piscina",
        "slug"=> "casa-campagna-piscina",
        "price_per_night"=> 220,
        "rooms_number"=> 3,
        "beds_number"=> 6,
        "bathrooms_number"=> 3,
        "square_meters"=> 160,
        "address"=> "Via dei Campi,12,Pisa",
        "latitude"=> "43.717137",
        "longitude"=> "10.403147",
        "cover_img"=> "img/app_10/cover-img-app-10.jpeg",
        "description"=> "Questa casa di campagna è circondata da campi verdi e vigne. La piscina privata è il luogo perfetto per rilassarsi e godersi il sole toscano.",
        "visible"=> 1
    ],
    [
        "id" => 11,
        "user_id" => 1,
        "title" => "Appartamento Moderno in Centro",
        "slug" => "appartamento-milano-centro",
        "price_per_night" => 150,
        "rooms_number" => 2,
        "beds_number" => 4,
        "bathrooms_number" => 1,
        "square_meters" => 80,
        "address" => "Via del Corso, 5, Milano",
        "latitude" => "45.465454",
        "longitude" => "9.186542",
        "cover_img" => "img/app_11/cover-img-app-11.jpeg",
        "description" => "Questo appartamento moderno si trova nel cuore di Milano, a pochi passi dai principali luoghi di interesse.",
        "visible" => 1
    ],
    [
        "id" => 12,
        "user_id" => 1,
        "title" => "Villetta con Giardino a Milano",
        "slug" => "villetta-milano-giardino",
        "price_per_night" => 180,
        "rooms_number" => 3,
        "beds_number" => 5,
        "bathrooms_number" => 2,
        "square_meters" => 120,
        "address" => "Via delle Rose, 10, Milano",
        "latitude" => "45.487623",
        "longitude" => "9.201354",
        "cover_img" => "img/app_12/cover-img-app-12.jpeg",
        "description" => "Questa villetta con giardino offre un'oasi di tranquillità nel cuore di Milano, ideale per famiglie o gruppi di amici.",
        "visible" => 1
    ],
    [
        "id" => 13,
        "user_id" => 2,
        "title" => "Loft Elegante in Zona Navigli",
        "slug" => "loft-milano-navigli",
        "price_per_night" => 200,
        "rooms_number" => 1,
        "beds_number" => 2,
        "bathrooms_number" => 1,
        "square_meters" => 70,
        "address" => "Via dei Navigli, 20, Milano",
        "latitude" => "45.459875",
        "longitude" => "9.177963",
        "cover_img" => "img/app_13/cover-img-app-13.jpeg",
        "description" => "Questo loft elegante si trova nella vivace zona dei Navigli e offre un design moderno e confortevole.",
        "visible" => 1
    ],
    [
        "id" => 14,
        "user_id" => 2,
        "title" => "Appartamento con Terrazza Panoramica",
        "slug" => "appartamento-milano-terrazza",
        "price_per_night" => 250,
        "rooms_number" => 4,
        "beds_number" => 6,
        "bathrooms_number" => 2,
        "square_meters" => 150,
        "address" => "Via Panoramica, 15, Milano",
        "latitude" => "45.471236",
        "longitude" => "9.209874",
        "cover_img" => "img/app_14/cover-img-app-14.jpeg",
        "description" => "Questo appartamento offre una spettacolare terrazza panoramica con vista sulla città di Milano.",
        "visible" => 1
    ],
    [
        "id" => 15,
        "user_id" => 3,
        "title" => "Casa Vicino al Duomo",
        "slug" => "casa-milano-duomo",
        "price_per_night" => 300,
        "rooms_number" => 5,
        "beds_number" => 8,
        "bathrooms_number" => 3,
        "square_meters" => 180,
        "address" => "Via Duomo, 1, Milano",
        "latitude" => "45.464785",
        "longitude" => "9.190345",
        "cover_img" => "img/app_15/cover-img-app-15.jpeg",
        "description" => "Questa casa si trova a pochi passi dal Duomo di Milano e offre ampi spazi per gruppi numerosi.",
        "visible" => 1
    ],
    [
        "id" => 16,
        "user_id" => 3,
        "title" => "Appartamento con Vista sui Navigli",
        "slug" => "appartamento-milano-navigli-vista",
        "price_per_night" => 180,
        "rooms_number" => 2,
        "beds_number" => 4,
        "bathrooms_number" => 1,
        "square_meters" => 85,
        "address" => "Via dei Canali, 8, Milano",
        "latitude" => "45.460932",
        "longitude" => "9.175642",
        "cover_img" => "img/app_16/cover-img-app-16.jpeg",
        "description" => "Questo appartamento offre una splendida vista sui Navigli e una posizione ideale per esplorare la zona.",
        "visible" => 1
    ],
    [
        "id" => 17,
        "user_id" => 4,
        "title" => "Villa di Lusso con Piscina",
        "slug" => "villa-milano-piscina",
        "price_per_night" => 500,
        "rooms_number" => 6,
        "beds_number" => 10,
        "bathrooms_number" => 4,
        "square_meters" => 300,
        "address" => "Via della Villa, 12, Milano",
        "latitude" => "45.478965",
        "longitude" => "9.216598",
        "cover_img" => "img/app_17/cover-img-app-17.jpeg",
        "description" => "Questa villa di lusso offre una piscina privata e tutti i comfort per un soggiorno indimenticabile a Milano.",
        "visible" => 1
    ],
    [
        "id" => 18,
        "user_id" => 4,
        "title" => "Appartamento Artistico in Brera",
        "slug" => "appartamento-milano-brera-artistico",
        "price_per_night" => 220,
        "rooms_number" => 3,
        "beds_number" => 5,
        "bathrooms_number" => 2,
        "square_meters" => 110,
        "address" => "Via degli Artisti, 7, Milano",
        "latitude" => "45.474369",
        "longitude" => "9.189725",
        "cover_img" => "img/app_18/cover-img-app-18.jpeg",
        "description" => "Questo appartamento artistico si trova nel quartiere di Brera ed è decorato con opere d'arte uniche.",
        "visible" => 1
    ],
    [
        "id" => 19,
        "user_id" => 5,
        "title" => "Penthouse con Terrazza Panoramica",
        "slug" => "penthouse-milano-terrazza",
        "price_per_night" => 350,
        "rooms_number" => 4,
        "beds_number" => 6,
        "bathrooms_number" => 3,
        "square_meters" => 200,
        "address" => "Via Panoramica, 25, Milano",
        "latitude" => "45.472518",
        "longitude" => "9.207432",
        "cover_img" => "img/app_19/cover-img-app-19.jpeg",
        "description" => "Questo elegante penthouse offre una terrazza panoramica con vista mozzafiato sulla città di Milano.",
        "visible" => 1
    ],
    [
        "id" => 20,
        "user_id" => 5,
        "title" => "Appartamento Storico a Milano",
        "slug" => "appartamento-milano-storico",
        "price_per_night" => 180,
        "rooms_number" => 2,
        "beds_number" => 4,
        "bathrooms_number" => 1,
        "square_meters" => 90,
        "address" => "Via Storica, 3, Milano",
        "latitude" => "45.466789",
        "longitude" => "9.200987",
        "cover_img" => "img/app_20/cover-img-app-20.jpeg",
        "description" => "Questo appartamento storico si trova in una zona ricca di storia e cultura a Milano, ideale per gli amanti dell'arte e della tradizione.",
        "visible" => 1
    ],
    [
        'id' => 21,
        'user_id' => 5,
        'title' => 'Appartamento nei dintorni di Milano',
        'slug' => 'appartamento-nei-dintorni-di-milano',
        'price_per_night' => 150,
        'rooms_number' => 3,
        'beds_number' => 5,
        'bathrooms_number' => 2,
        'square_meters' => 100,
        'address' => 'Via Campania, 4, Milano',
        'latitude' => '45.203902',  
        'longitude' => '9.162068',  
        'cover_img' => 'img/app_21/cover-img-app-21.jpeg',
        'description' => 'Questo appartamento si trova nei dintorni di Milano, a soli 25 km dal centro, offrendo una posizione tranquilla e comoda per esplorare la città.',
        'visible' => 1
    ]
];